"""20 extended alpha harnesses — HERMES, NOVA clean internet, Web3 edge, recursive AI."""

from __future__ import annotations

from typing import List

from mesie.harness.alpha_registry import AlphaHarness

ALPHA_EXTENDED: List[AlphaHarness] = [
    AlphaHarness(
        "hermes_fleet",
        "HERMES 12-Worker Cloudflare Fleet",
        "edge_execution",
        "wrangler + ICP CLI + SDK one-shot",
        ".\\Start-HermesFleet.ps1",
        "deliverables/hermes/HERMES_FLEET_MANIFEST.json",
        "ops-triad",
        ("edge", "web3", "platform"),
        ("hermes_fleet", "api_console", "deploy_shot"),
        "12 Cloudflare workers — ingest, embed, validate, ICP, deploy. NOVA PROTOCOL.",
    ),
    AlphaHarness(
        "nova_clean_internet",
        "NOVA Clean Internet Protocol",
        "clean_feed",
        "HERMES H11 + spectral validate gate",
        "python -m mesie.hermes.nova_protocol",
        "deliverables/hermes/NOVA_PROTOCOL_HERMES.json",
        "intel-triad",
        ("ai_safety", "ingest", "sovereign"),
        ("hermes_fleet", "platform_hub"),
        "Clean internet feeds for recursive AI — ItsnotAILabs doctrine.",
    ),
    AlphaHarness(
        "hermes_wrangler_forge",
        "HERMES Wrangler Forge",
        "deploy_config",
        "auto wrangler.toml per worker",
        "python scripts/forge_hermes_fleet.py",
        "deliverables/hermes/wrangler.toml",
        "ops-triad",
        ("edge", "cloudflare"),
        ("hermes_fleet", "api_console"),
        "H07 — generates wrangler.toml for all 12 workers + routes.",
    ),
    AlphaHarness(
        "hermes_icp_embed",
        "HERMES ICP Cloud Embed",
        "web3_sovereign",
        "ICP CLI + colony fleet anchor",
        "python -m mesie.cloud.icp_bridge --manifest",
        "deliverables/hermes/icp/HERMES_ICP_CLI.json",
        "research-triad",
        ("icp", "sovereign", "web3"),
        ("hermes_fleet", "enterprise_4k"),
        "H06 — ICP canister deploy scripts; HERMES embedded in ICP clouds.",
    ),
    AlphaHarness(
        "hermes_deploy_shot",
        "HERMES One-Shot Deploy",
        "execution_interface",
        "forge → wrangler → ICP → SDK",
        "deliverables/hermes/deploy.ps1",
        "deliverables/hermes/DEPLOY_SHOT.json",
        "executioner",
        ("all_industries",),
        ("hermes_fleet", "dashboard_4k"),
        "H12 — ready-to-run execution interface for edge + ICP ship.",
    ),
    AlphaHarness(
        "itsnotailabs_recursive",
        "ItsnotAILabs Recursive AI Loop",
        "recursive_ml",
        "Producer + HERMES ingest + NOVA pulse",
        "python -m mesie.ml.producer",
        "deliverables/ml/PRODUCER_STATE.json",
        "intel-triad",
        ("neuroai", "microai", "recursive"),
        ("producer_lab", "hermes_fleet"),
        "Recursive AI systems — corpus harvest, embed depth, runtime pulse.",
    ),
    AlphaHarness(
        "neuroai_microai_bridge",
        "NeuroAI ↔ MicroAI Bridge",
        "cognitive_edge",
        "NeuroAIX + NOVA micro fleet",
        "python -m mesie.sdk.neuroaix_engine",
        "deliverables/platform/UNIFIED_MODEL_CATALOG.json",
        "research-triad",
        ("neuroai", "microai"),
        ("model_hub", "reality_engine"),
        "Connectome intelligence bound to 70-career micro agents.",
    ),
    AlphaHarness(
        "web3_sovereign_ingest",
        "Web3 Sovereign Ingest Lane",
        "decentralized_ingest",
        "HERMES ingest + ICP receipt chain",
        "POST /processor/hermes/hermes-ingest/invoke",
        "deliverables/hermes/packages/hermes-ingest.json",
        "quality-triad",
        ("web3", "sovereign", "ingest"),
        ("hermes_fleet", "api_console"),
        "Decentralized alternative to centralized AI data pipelines.",
    ),
    AlphaHarness(
        "edge_embed_lane",
        "Edge Embed Lane",
        "embedding_edge",
        "H02 ST-φ Cloudflare proxy",
        "POST /processor/hermes/hermes-embed/invoke",
        "deliverables/hermes/packages/hermes-embed.json",
        "ops-triad",
        ("edge", "embedding"),
        ("model_hub", "hermes_fleet"),
        "Sub-ms spectral embed at Cloudflare edge — no torch.",
    ),
    AlphaHarness(
        "json_corpus_ingest_pack",
        "JSON Corpus Ingest Pack",
        "large_data",
        "H09 JSONL packages for AI ingesting",
        "POST /processor/hermes/hermes-json-corpus/invoke",
        "deliverables/ml/CORPUS.jsonl",
        "intel-triad",
        ("ml", "ingest", "embedding"),
        ("producer_lab", "hermes_fleet"),
        "932+ JSONL records packaged for edge ingestion workflows.",
    ),
    AlphaHarness(
        "sdk_one_shot_pack",
        "SDK One-Shot Pack",
        "sdk_bundle",
        "H08 MAESI + HERMES TypeScript clients",
        "python scripts/forge_hermes_fleet.py",
        "deliverables/hermes/sdk/HERMES_SDK_MANIFEST.json",
        "creator",
        ("sdk", "typescript", "python"),
        ("hermes_fleet", "api_console"),
        "ingest_client, embed_client, clean_feed SDK stubs + zip.",
    ),
    AlphaHarness(
        "federated_envelope_edge",
        "Federated Envelope Edge",
        "mcp_federation",
        "H05 MCP envelope at Cloudflare",
        "POST /processor/hermes/hermes-envelope/invoke",
        "deliverables/hermes/packages/hermes-envelope.json",
        "intel-triad",
        ("mcp", "federation"),
        ("platform_hub", "hermes_fleet"),
        "Cross-AI tool invoke wrapped for edge workers.",
    ),
    AlphaHarness(
        "spectral_validate_edge",
        "Spectral Validate Edge",
        "quality_gate",
        "H03 schema levels 1–6 at edge",
        "POST /processor/hermes/hermes-validate/invoke",
        "deliverables/hermes/packages/hermes-validate.json",
        "quality-triad",
        ("quality", "schema"),
        ("hermes_fleet", "model_hub"),
        "Validate before ingest — clean internet gate.",
    ),
    AlphaHarness(
        "ann_retrieval_worker",
        "ANN Retrieval Worker",
        "retrieval_edge",
        "H04 Fast ANN at edge",
        "POST /processor/hermes/hermes-match/invoke",
        "deliverables/hermes/packages/hermes-match.json",
        "ops-triad",
        ("retrieval", "ann"),
        ("computing_family", "hermes_fleet"),
        "Band-sign LSH cosine search proxied through Cloudflare.",
    ),
    AlphaHarness(
        "mcp_colony_hermes_sync",
        "MCP Colony HERMES Sync",
        "colony_fleet",
        "Fleet MCP + HERMES deploy pack",
        "python mcp-colonies/fleet-server/server.py",
        "deliverables/hermes/HERMES_FLEET_MANIFEST.json",
        "ops-triad",
        ("mcp", "fleet", "colony"),
        ("enterprise_4k", "hermes_fleet"),
        "Sovereign colony fleet pulses HERMES worker status.",
    ),
    AlphaHarness(
        "recursive_ml_loop_edge",
        "Recursive ML Loop Edge",
        "recursive_edge",
        "Producer cycle via HERMES H09",
        "POST /processor/platform/producer-pipeline/invoke",
        "deliverables/ml/PRODUCER_FEED.jsonl",
        "research-triad",
        ("ml", "recursive", "edge"),
        ("producer_lab", "hermes_fleet"),
        "Always-on ML recursive loop at edge execution interface.",
    ),
    AlphaHarness(
        "clean_internet_alpha_suite",
        "Clean Internet Alpha Suite",
        "alpha_proof",
        "H11 + validate + ingest triad",
        "python -m pytest tests/test_hermes_fleet.py -q",
        "deliverables/hermes/NOVA_PROTOCOL_HERMES.json",
        "quality-triad",
        ("ai_safety", "ingest"),
        ("hermes_fleet", "platform_hub"),
        "Full clean-feed alpha proof — 13/13 eval style gate for feeds.",
    ),
    AlphaHarness(
        "icp_cloud_hermes_anchor",
        "ICP Cloud HERMES Anchor",
        "icp_anchor",
        "Bridge sync + HERMES receipt",
        "python -m mesie.cloud.icp_bridge",
        "deliverables/icp/ICP_BRIDGE_SYNC_STATE.json",
        "research-triad",
        ("icp", "web3", "proof"),
        ("hermes_fleet", "enterprise_4k"),
        "Anchor edge HERMES proofs to sovereign ICP canisters.",
    ),
    AlphaHarness(
        "cloudflare_fleet_pulse",
        "Cloudflare Fleet Pulse",
        "fleet_health",
        "12-worker health sweep",
        "GET /processor/hermes",
        "deliverables/hermes/HERMES_FLEET_MANIFEST.json",
        "ops-triad",
        ("cloudflare", "edge"),
        ("hermes_fleet", "computing_family"),
        "Pulse all 12 HERMES workers — routes, packages, wrangler state.",
    ),
    AlphaHarness(
        "design_reality_hermes",
        "Design Reality + HERMES",
        "reality_edge",
        "Reality engine + clean feed orchestrate",
        "GET /processor/design",
        "deliverables/design/DESIGN_ECOSYSTEM_MANIFEST.json",
        "creator",
        ("design", "reality", "edge"),
        ("reality_engine", "hermes_fleet"),
        "100 Latin agents + HERMES clean internet showcase layer.",
    ),
    AlphaHarness(
        "platform_hermes_mvp",
        "Platform MVP + HERMES Bridge",
        "mvp_bridge",
        "Platform hub + HERMES fleet unified",
        ".\\Start-ModelPlatforms.ps1; .\\Start-HermesFleet.ps1",
        "deliverables/platform/PLATFORM_MANIFEST.json",
        "orchestrator",
        ("platform", "edge", "mvp"),
        ("platform_hub", "hermes_fleet"),
        "MVP web apps wired to HERMES 12-worker execution interface.",
    ),
]