"""Native MESIE / MAESI / NeuroAIX tool and skill registry."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class NativeTool:
    id: str
    name: str
    skill_name: str
    category: str
    description: str
    triggers: List[str]
    command: str
    deliverable: Optional[str] = None
    requires: List[str] = field(default_factory=list)


TOOLS: List[NativeTool] = [
    # --- Core MESIE ---
    NativeTool("validate", "Validate Record", "mesie-validate", "core",
               "Validate spectral JSON against MESIE schema levels 1-6.",
               ["validate", "schema", "quality check"], "python examples/01_load_and_validate.py"),
    NativeTool("match", "Match Two Spectra", "mesie-match", "core",
               "Compare two spectral records with composite scoring.",
               ["match", "similarity", "compare spectra"], "python examples/02_match_two_records.py"),
    NativeTool("generate-psd", "Generate PSD", "mesie-generate", "core",
               "Synthesize power spectral density record (seeded).",
               ["generate psd", "synthetic psd"], "python examples/03_generate_psd.py"),
    NativeTool("generate-fas", "Generate FAS", "mesie-generate", "core",
               "Synthesize Fourier amplitude spectrum.",
               ["generate fas"], "python examples/04_generate_fas.py"),
    NativeTool("rotdnn", "RotDNN Workflow", "mesie-generate", "core",
               "RotDNN orientation spectral workflow.",
               ["rotdnn", "orientation"], "python examples/05_rotdnn_workflow.py"),
    NativeTool("embed", "Create Embedding", "mesie-embed", "core",
               "Vectorize a spectral record with SpectralVectorizer.",
               ["embed", "vectorize", "embedding"], "python examples/06_create_spectral_embedding.py"),
    NativeTool("bundled-data", "Load Bundled Data", "mesie-data", "core",
               "Load references, benchmarks, spectral library.",
               ["bundled data", "references", "benchmarks"], "python examples/09_load_bundled_data.py"),
    NativeTool("rank", "Rank Candidates", "mesie-match", "core",
               "Rank a query spectrum against a candidate pool (composite scoring).",
               ["rank", "rank candidates", "retrieval", "top-k"],
               "python scripts/run_rank_demo.py"),
    NativeTool("fix-data", "Fix Reference Data", "mesie-data", "core",
               "Repair bundled reference JSON (negative amplitudes, schema drift).",
               ["fix data", "repair references", "data quality"],
               "python scripts/fix_reference_data.py"),
    # --- Fingerprint / ANN ---
    NativeTool("fingerprint", "Fingerprint ANN Pipeline", "mesie-fingerprint", "retrieval",
               "TF → salient → LSH → approximate nearest neighbors.",
               ["fingerprint", "lsh", "ann", "time-frequency", "salient"],
               "python examples/13_fingerprint_ann_pipeline.py",
               "library/spectral_index.json"),
    NativeTool("embed-library", "Embed Full Library", "mesie-embed-library", "retrieval",
               "Embed all references + benchmarks into spectral_index.json.",
               ["embed library", "index corpus"], "python scripts/embed_spectral_library.py",
               "library/spectral_index.json"),
    NativeTool("embed-mine", "Embed User Library", "mesie-embed-library", "retrieval",
               "Embed your JSON folder into my_spectral_index.json.",
               ["my library", "embed folder"], "python scripts/embed_my_library.py <folder> --octopus",
               "library/my_spectral_index.json"),
    # --- Octopus / Internal API ---
    NativeTool("octopus", "Octopus Engineering", "mesie-octopus", "orchestration",
               "Eight-arm controller; EMBED/MATCH default to AISVectorPolyglot (vector + Rust/Python).",
               ["octopus", "eight arms", "internal api", "multi-arm", "polyglot arms"],
               "python examples/11_octopus_internal_api.py"),
    NativeTool("ais-polyglot", "AISVectorPolyglot Suite", "mesie-polyglot", "orchestration",
               "Polyglot test/use/integration: Python, Rust, Julia, Motoko, TypeScript + vector + AIS + 3rd-party AI.",
               ["ais", "polyglot", "julia", "rust", "motoko", "typescript", "vector bridge", "third party ai"],
               "python scripts/run_ais_polyglot_suite.py",
               "deliverables/AISVectorPolyglot_Integration_Report.json"),
    NativeTool("internal-bus", "Internal API Bus", "mesie-internal", "orchestration",
               "Register all engines on InternalBus; validate + match routing demo.",
               ["internal bus", "internal api", "engine bus", "message envelope"],
               "python scripts/run_internal_bus_demo.py"),
    NativeTool("engines", "List Engines", "mesie-internal", "orchestration",
               "Print registered engine names from default registry.",
               ["engines", "engine registry", "nine engines"],
               'python -c "from mesie.engines.registry import build_default_registry; r=build_default_registry(); print(\', \'.join(sorted(r.names())))"'),
    # --- MAESI SDK ---
    NativeTool("logic-prover", "SOLUS Logic Prover", "mesie-logic-prover", "solus",
               "SOLUS Logic formal model — proof layer in Logic ⊗ Reasoning ⊗ Emergence ⊗ Adaptation.",
               ["logic prover", "proof", "theorem", "solus math"], "python scripts/run_solus_math_caretakers.py",
               "deliverables/SOLUS_Math_Caretakers_Report.json"),
    NativeTool("pattern-forge", "SOLUS Pattern Forge", "mesie-pattern-forge", "solus",
               "Your X-ray math caretaker — z-depth, spectral decompose, phi-harmonics, fully local.",
               ["pattern forge", "xray", "z-depth", "spectral decompose", "solus math"],
               "python scripts/run_solus_math_caretakers.py",
               "deliverables/SOLUS_Math_Caretakers_Report.json"),
    NativeTool("solus-organism", "SOLUS SDK Organism", "mesie-solus-organism", "solus",
               "Four own formal models: Logic, Reasoning, Emergence, Adaptation — zero third-party.",
               ["solus", "organism", "caretaker", "formal model", "logic", "reasoning", "emergence", "adaptation", "sovereign"],
               "python scripts/run_solus_math_caretakers.py",
               "deliverables/SOLUS_Math_Caretakers_Report.json"),
    NativeTool("maesi", "MAESI SDK Run", "mesie-maesi", "maesi",
               "Run MAESI v1.1: laws, elements, bio, technical + research knowledge, fast compute.",
               ["maesi", "maesi sdk", "neuroaix sdk"], "python scripts/run_maesi_sdk.py",
               "deliverables/MAESI_SDK_Run_Report.json"),
    NativeTool("native-ai", "Native Local AI Deliverables", "mesie-native-ai", "maesi",
               "Fused SOLUS native AI: stream + generate JSON/MD deliverables inside SDK (vault + tokens).",
               ["native ai", "stream", "generate", "deliverable", "local ai", "solus sdk"],
               "python scripts/run_native_ai_deliverables.py",
               "deliverables/native_ai/NativeAI_Manifest.json"),
    NativeTool("knowledge", "Research Knowledge Search", "mesie-knowledge", "maesi",
               "Search technical + research catalogs.",
               ["research", "technical library", "knowledge"],
               'python -c "from mesie.sdk import search_research; print(search_research(\'LSH ANN\', 5))"'),
    NativeTool("fast-compute", "Fast Compute Benchmark", "mesie-maesi", "maesi",
               "Batch matrix cosine vs loop match — virtual-chip throughput.",
               ["fast compute", "batch match", "speedup", "virtual chip"],
               "python scripts/run_fast_compute_benchmark.py",
               "deliverables/MAESI_Fast_Compute_Benchmark.json"),
    # --- NeuroAIX ---
    NativeTool("neuroaix", "NeuroAIX Connectome", "mesie-neuroaix", "neuroaix",
               "MAESI observation encoder + 3D connectome brain demo.",
               ["neuroaix", "connectome", "brain regions"],
               "python examples/08_3d_connectome_brain.py"),
    NativeTool("cognitive", "Cognitive Memory", "mesie-neuroaix", "neuroaix",
               "Spectral memory adapter and agent state.",
               ["cognitive", "memory adapter"], "python examples/07_cognitive_memory_adapter.py"),
    # --- Domain analysis ---
    NativeTool("domains", "Multi-Domain Suites", "mesie-domains", "analysis",
               "Terrain, robotics, orbital, power, seismic analysis suites.",
               ["domains", "terrain", "robotics", "power", "seismic suites"],
               "python scripts/run_multi_domain_suites.py",
               "deliverables/MESIE_Multi_Domain_Suite_Report.md"),
    NativeTool("orbital", "Orbital Edge 50d", "mesie-orbital", "analysis",
               "50 days back + 50 forward orbital-edge analysis.",
               ["orbital", "satellite edge", "50 day"], "python scripts/orbital_edge_50d_analysis.py",
               "scripts/orbital_edge_50d_report.json"),
    NativeTool("enterprise-ai", "Enterprise AI Copilot", "mesie-enterprise-ai", "enterprise_ai",
               "Sovereign enterprise AI: agent memory, SOLUS MEMORY, receipt chain, sovereign vault for embedded minted tokens.",
               ["enterprise ai", "agent memory", "copilot", "sovereign ai", "agentic", "receipt chain", "minted token", "sovereign vault"],
               "python scripts/run_enterprise_ai_suite.py",
               "deliverables/Enterprise_AI_Suite_Report.json"),
    NativeTool("monte-carlo", "Monte Carlo Enterprise", "mesie-enterprise", "enterprise_ai",
               "Monte Carlo benchmark across 10 enterprise use cases (incl. AI agent spectral memory).",
               ["monte carlo", "enterprise", "sla benchmark"],
               "python scripts/monte_carlo_enterprise_benchmark.py --trials 200 --benchmark",
               "deliverables/MESIE_Monte_Carlo_Enterprise_Report.md"),
    NativeTool("multi-enterprise-20", "Multi-Enterprise 20", "mesie-enterprise", "enterprise_ai",
               "20 tests: 10 industries on enterprise-v2 benchmarks + 10 enterprise AI stack checks.",
               ["multi enterprise", "enterprise 20", "enterprise uses"],
               "python scripts/run_multi_enterprise_20.py --trials 50",
               "deliverables/MESIE_Multi_Enterprise_20_Report.md"),
    NativeTool("sovereign-local-120", "Sovereign Local 120", "mesie-solus-organism", "enterprise_ai",
               "120-test sovereign local suite: SOLUS, enterprise, octopus, native AI, core, resilience.",
               ["sovereign local", "sovereign mode", "offline local", "own models only"],
               "python scripts/run_sovereign_local_suite.py",
               "deliverables/MESIE_Sovereign_Local_120_Report.md"),
    NativeTool("field-access", "Field Access Bridge", "mesie-solus-organism", "enterprise_ai",
               "Airgapped world-computer access via frequency field alignment — no WiFi, no third-party.",
               ["field access", "airgapped", "world computer", "frequency bridge", "schumann", "eco hz"],
               "python scripts/run_field_access_suite.py",
               "deliverables/MESIE_Field_Access_Report.json"),
    NativeTool("field-route", "Field Route", "mesie-solus-organism", "enterprise_ai",
               "Production field router — alias routing (ground→world, leo→geo), policies, health.",
               ["field route", "route", "world computer route", "ground to world"],
               "python scripts/field_route.py list"),
    NativeTool("field-route-run", "Field Route Path", "mesie-solus-organism", "enterprise_ai",
               "Compute a field route between two nodes or aliases.",
               ["field route path", "route ground world"],
               "python scripts/field_route.py route ground world"),
    NativeTool("neuroswarm-audit", "NeuroSwarm Audit Evidence", "mesie-neuroswarm-audit", "enterprise_ai",
               "Evidence-backed audit responses for NeuroSwarmAI.com claims — latency, swarm, adversarial.",
               ["neuroswarm", "audit evidence", "claims verifier", "latency harness", "12ms"],
               "python scripts/run_neuroswarm_audit.py --trials 1000",
               "deliverables/NeuroSwarmAI_Audit_Evidence.json"),
    NativeTool("pro-update", "Pro Update Suite", "mesie-enterprise-ai", "enterprise_ai",
               "Specialized-general expansion: domains, CSV/UDP ingest, hive mesh, external benchmarks.",
               ["pro update", "specialized general", "field ingest", "hive mind", "external benchmark"],
               "python scripts/run_pro_update_suite.py --trials 200",
               "deliverables/MESIE_Pro_Update_Report.json"),
    NativeTool("drone-swarm", "Drone Swarm Coordination", "mesie-drone-swarm", "enterprise_ai",
               "Decentralized drone swarm doctrine — gossip consensus, jam failover, 10K scale.",
               ["drone swarm", "swarm coordination", "decentralized", "chimeria", "10k nodes"],
               "python scripts/run_drone_swarm_suite.py --agents 10000",
               "deliverables/NeuroSwarmAI_Drone_Swarm_Report.json"),
    NativeTool("major-benchmarks", "Major Third-Party Benchmarks", "mesie-benchmark", "qa",
               "MLPerf-class, vector DB, MQTT, cloud LLM, swarm — SDK v1.4 comparison harness.",
               ["major benchmarks", "third party", "mlperf", "faiss", "mqtt", "pinecone"],
               "python scripts/run_sdk_major_benchmarks.py --trials 300 --agents 10000",
               "deliverables/MAESI_SDK_Major_Benchmarks.json"),
    NativeTool("production-tiers", "Production Tier 1+2", "mesie-enterprise-ai", "enterprise_ai",
               "On-prem appliance manifest + virtual silicon + cluster swarm + OTA mesh + MLPerf.",
               ["production", "tier1", "tier2", "appliance", "mlperf submit", "virtual silicon"],
               "python scripts/run_production_tiers.py --tier both",
               "deliverables/MESIE_Production_Tiers_Report.json"),
    NativeTool("interior-datacenter", "Interior Data Center", "mesie-enterprise-ai", "enterprise_ai",
               "Sovereign corpus vault inside your org — gathers bundled references, libraries, scenarios.",
               ["interior datacenter", "corpus vault", "sovereign dc", "data center"],
               "python scripts/run_interior_datacenter.py",
               "deliverables/MESIE_Interior_DataCenter_Manifest.json"),
    NativeTool("cluster-edge", "Cluster Edge Fabric", "mesie-enterprise-ai", "enterprise_ai",
               "Interior DC + OTA mesh + STAR swarm — LAN cluster edge, no cloud.",
               ["cluster edge", "lan cluster", "multi node", "edge fabric"],
               "python scripts/run_cluster_edge.py --nodes 4 --agents 1000",
               "deliverables/MESIE_Cluster_Edge_Report.json"),
    NativeTool("deployment-doctrine", "Deployment Doctrine", "mesie-neuroswarm-audit", "enterprise_ai",
               "Edge contested + industry contractor framing — not cloud-first.",
               ["deployment doctrine", "edge contested", "gsa contractor", "third way"],
               "python scripts/run_interior_datacenter.py",
               "deliverables/MESIE_Deployment_Doctrine.json"),
    NativeTool("virtual-silicon", "Virtual Silicon VS1", "mesie-laptop", "analysis",
               "Virtual chip certification — RF HIL, OTA multicast mesh, MLPerf lane.",
               ["virtual silicon", "virtual chip", "rf hil", "ota mesh"],
               "python scripts/run_virtual_silicon_suite.py",
               "deliverables/virtual_silicon/MESIE_Virtual_Silicon_Report.json"),
    NativeTool("drone-thesis", "Drone Defense+Offense Thesis", "mesie-enterprise-ai", "enterprise_ai",
               "Enterprise thesis validation — EW defense, strike offense, measured report.",
               ["thesis", "drone defense", "drone offense", "enterprise", "chimeria"],
               "python scripts/run_enterprise_drone_thesis.py",
               "deliverables/MESIE_Enterprise_Drone_Defense_Offense_Thesis.md"),
    NativeTool("scenario-sim", "Scenario Simulation Suite", "mesie-domains", "domains",
               "Military drone + enterprise civilian scenarios backed by real reference data.",
               ["scenario", "simulation", "military data", "enterprise use case", "drone"],
               "python scripts/run_scenario_simulation_suite.py",
               "deliverables/MESIE_Scenario_Simulation_Report.json"),
    NativeTool("mission-world-week", "Mission World Week Sim", "mesie-drone-swarm", "domains",
               "7-day theater simulation — real data hierarchy, operational narrative.",
               ["mission world", "week simulation", "theater", "campaign"],
               "python scripts/run_mission_world_week.py --days 7",
               "deliverables/mission_worlds/military_theater_week_001_week_report.json"),
    NativeTool("is-this-true", "Is This True?", "mesie-neuroswarm-audit", "enterprise_ai",
               "Honest Grok/X verification — evidence tiers, not marketing yes.",
               ["is this true", "verification", "grok critique", "trust"],
               "python scripts/run_is_this_true.py",
               "deliverables/Is_This_True_Response.json"),
    NativeTool("proof-substrate", "Proof Substrate", "mesie-neuroswarm-audit", "enterprise_ai",
               "Sealed hash-linked evidence graph — claims, artifacts, reproduce commands.",
               ["proof substrate", "evidence graph", "seal", "hash chain", "substrate"],
               "python scripts/run_proof_substrate.py",
               "deliverables/Proof_Substrate.json"),
    NativeTool("trust-agents", "Trust Remediation Agents", "mesie-enterprise-ai", "enterprise_ai",
               "Auto agents: audit gaps, run harnesses, commit production-readiness branch.",
               ["trust agents", "remediation", "commit", "production readiness"],
               "python scripts/run_trust_remediation_agents.py",
               "deliverables/Trust_Remediation_Report.json"),
    NativeTool("neuroswarm-readiness", "NeuroSwarmAI.com Readiness", "mesie-neuroswarm-audit", "enterprise_ai",
               "Gap closure plan + website evidence pack for neuroswarmai.com.",
               ["readiness", "neuroswarmai.com", "gap closure", "production"],
               "python scripts/run_neuroswarm_readiness.py",
               "deliverables/neuroswarmai_com/evidence_manifest.json"),
    NativeTool("laptop", "Laptop Research Report", "mesie-laptop", "analysis",
               "Virtual chip framing + embedded library report.",
               ["laptop", "virtual chip", "research report"],
               "python scripts/embed_spectral_library.py && python scripts/generate_laptop_research_report.py",
               "deliverables/MESIE_Laptop_Research_Report.md"),
    # --- QA / Speed ---
    NativeTool("test", "Run Test Suite", "mesie-test", "qa",
               "Run full pytest suite.",
               ["test", "pytest", "ci"], "python -m pytest tests/ -q"),
    NativeTool("benchmark", "Speed Benchmark", "mesie-benchmark", "qa",
               "Determinism and match/embed throughput.",
               ["benchmark", "speed", "determinism"], "python scripts/determinism_benchmark.py"),
    NativeTool("sdk-drive", "SDK Test Drive", "mesie-test", "qa",
               "End-to-end SDK smoke with report JSON.",
               ["sdk test drive", "smoke test"], "python scripts/sdk_test_drive.py",
               "scripts/sdk_test_drive_report.json"),
    # --- Deploy ---
    NativeTool("cloudflare", "Cloudflare Worker", "mesie-deploy", "deploy",
               "Edge API deploy guide and worker health.",
               ["cloudflare", "worker", "edge api", "deploy"],
               "type docs\\cloudflare.md"),
    NativeTool("catalog", "Export Tool Catalog", "mesie-deploy", "deploy",
               "Write JSON catalog of all native tools and skills.",
               ["catalog", "tool list", "skills map"],
               "python -m mesie.tools.cli catalog",
               "deliverables/MESIE_Native_Tools_Catalog.json"),
    NativeTool("mesie-shell", "MESIE Terminal Shell", "mesie-deploy", "deploy",
               "PowerShell-first interactive shell + open-terminal surfaces.",
               ["powershell", "terminal", "shell", "mesie.ps1", "open terminal"],
               "python -m mesie.tools.cli shell"),
    NativeTool("open-terminal", "Open OS Terminal", "mesie-deploy", "deploy",
               "Spawn PowerShell / Windows Terminal at repo root with SDK loaded.",
               ["open terminal", "windows terminal", "wt", "enter shell"],
               "powershell -ExecutionPolicy Bypass -File scripts/Enter-MESIEShell.ps1"),
    NativeTool("maesi-copilot", "MAESI AI Copilot Terminal", "mesie-native-ai", "maesi",
               "Terminal + sovereign/Sam.gov/research AI — default after pip install.",
               ["maesi", "copilot", "terminal ai", "sovereign ai"],
               "maesi --tier sovereign"),
    NativeTool("samgov-edition", "Sam.gov Contractor Edition", "mesie-enterprise-ai", "enterprise_ai",
               "GSA contractor workflows — proof, readiness, opportunity alignment.",
               ["sam.gov", "gsa", "contractor", "government"],
               "python scripts/run_samgov_suite.py",
               "deliverables/MESIE_SamGov_Contractor_Edition.json"),
    NativeTool("sync-auro-substrate", "Sync Auro Substrate", "mesie-neuroaix", "neuroaix",
               "Pull GPTREPO PROTO-183 + NeuroAI Paper IV into MESIE vendored fallback.",
               ["sync auro", "gptrepo", "substrate", "socp"],
               "python scripts/sync_auro_substrate.py",
               "data/neuroai/substrate/sync_manifest.json"),
    NativeTool("auro-speaking", "Auro Native Speaking Intelligence", "mesie-neuroaix", "neuroaix",
               "Medina native speaking AI — AuroNativeLM-v1 built per Paper IV. Zero third-party inference.",
               ["auro", "speaking intelligence", "native voice", "alpha family", "thesis defer", "socp"],
               "python scripts/run_auro_suite.py",
               "deliverables/Auro_Native_Speaking_Manifest.json"),
    NativeTool("auro-eval", "Auro Speaking Eval Suite", "mesie-neuroaix", "neuroaix",
               "Voice-memory, role-coherence, affect-calibration, boundary speech evaluations.",
               ["auro eval", "speaking eval", "role coherence", "voice memory"],
               "python scripts/run_auro_eval.py",
               "deliverables/Auro_Eval_Report.json"),
    NativeTool("release-ready", "Release Readiness Gate", "mesie-deploy", "deploy",
               "Bootstrap + copilot tiers + pytest gate for 0.3.4 release.",
               ["release", "release ready", "ship"],
               "python scripts/run_release_ready.py",
               "deliverables/MESIE_Release_Readiness.json"),
    NativeTool("mesie-bootstrap", "Install Bootstrap", "mesie-deploy", "deploy",
               "Embed terminal + copilot to ~/.mesie on install.",
               ["bootstrap", "install", "pip install"],
               "mesie-bootstrap --install-profile"),
]


SKILL_CATEGORIES = {
    "enterprise_ai": "Enterprise AI — Agent Memory & Sovereign Copilots",
    "solus": "SOLUS Local Math AI Caretakers",
    "core": "MESIE Core Spectral Engine",
    "retrieval": "Embedding, Fingerprint & ANN Retrieval",
    "orchestration": "Octopus & Internal API",
    "maesi": "MAESI SDK & Knowledge",
    "neuroaix": "NeuroAIX Connectome & Cognitive",
    "analysis": "Domain & Enterprise Analysis",
    "qa": "Quality Assurance & Benchmarks",
    "deploy": "Deploy & Edge",
}


def tool_by_id(tool_id: str) -> Optional[NativeTool]:
    for t in TOOLS:
        if t.id == tool_id:
            return t
    return None


def tools_by_category(category: str) -> List[NativeTool]:
    return [t for t in TOOLS if t.category == category]


def all_skill_names() -> List[str]:
    return sorted({t.skill_name for t in TOOLS})