"""Write deploy sandbox bundles per service."""

from __future__ import annotations

import hashlib
import json
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

from mesie.deploy.manifest import export_service_manifest, write_manifest
from mesie.deploy.registry import LOOM_EXTERNAL, SERVICE_REGISTRY, ServiceDefinition, get_service

ROOT = Path(__file__).resolve().parents[2]
SANDBOX_ROOT = ROOT / "deliverables" / "deploy" / "sandbox"
CATALOG_PATH = ROOT / "deliverables" / "deploy" / "MESIE_Service_Catalog.json"


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def _launcher_ps1(svc: ServiceDefinition) -> str:
    title = svc.powershell_title or svc.name
    env_lines = "\n".join(f'$env:{k} = "{v}"' for k, v in svc.env.items())
    cmd = " ".join(f'"{c}"' if " " in c else c for c in svc.start_command())
    return f"""# {title} — generated by mesie.deploy
$ErrorActionPreference = "Stop"
$Root = if ($env:MESIE_ROOT) {{ $env:MESIE_ROOT }} else {{ "{ROOT}" }}
$env:MESIE_ROOT = $Root
{env_lines}

Write-Host "{title}"
Write-Host "  command: {cmd}"
Write-Host ""

Set-Location $Root
{cmd}
"""


def _launcher_sh(svc: ServiceDefinition) -> str:
    env_lines = "\n".join(f'export {k}="{v}"' for k, v in svc.env.items())
    cmd = " ".join(svc.start_command())
    return f"""#!/usr/bin/env bash
# {svc.name} — generated by mesie.deploy
set -euo pipefail
export MESIE_ROOT="${{MESIE_ROOT:-{ROOT}}}"
{env_lines}
cd "$MESIE_ROOT"
exec {cmd}
"""


def _mcp_snippet(svc: ServiceDefinition) -> Optional[Dict[str, Any]]:
    if not svc.mcp_server_path or not svc.mcp_key:
        return None
    import sys

    return {
        "mcpServers": {
            svc.mcp_key: {
                "command": sys.executable,
                "args": [svc.mcp_server_path],
                "env": {
                    **svc.env,
                    "MESIE_PROCESSOR_URL": f"http://{svc.host}:{svc.port}" if svc.port else "http://127.0.0.1:8750",
                },
            }
        },
        "note": "Dry-run artifact only. Apply via: python scripts/package_services.py --deploy virtual-processor --target cursor-mcp --apply",
    }


def package_service(service_id: str, *, sandbox_root: Optional[Path] = None) -> Path:
    svc = get_service(service_id)
    out_dir = (sandbox_root or SANDBOX_ROOT) / service_id
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest_path = out_dir / "manifest.json"
    export_service_manifest(service_id, manifest_path)

    launcher_ps1 = out_dir / "launcher.ps1"
    launcher_ps1.write_text(_launcher_ps1(svc), encoding="utf-8")

    launcher_sh = out_dir / "launcher.sh"
    launcher_sh.write_text(_launcher_sh(svc), encoding="utf-8")

    mcp_path = out_dir / "mcp-snippet.json"
    snippet = _mcp_snippet(svc)
    if snippet:
        mcp_path.write_text(json.dumps(snippet, indent=2) + "\n", encoding="utf-8")

    checksums: Dict[str, str] = {}
    for p in (manifest_path, launcher_ps1, launcher_sh):
        if p.exists():
            checksums[p.name] = _sha256_file(p)[:16]
    if mcp_path.exists():
        checksums["mcp-snippet.json"] = _sha256_file(mcp_path)[:16]

    bundle = {
        "service_id": service_id,
        "ready": True,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "definition": svc.to_dict(),
        "paths": {
            "sandbox": str(out_dir),
            "manifest": str(manifest_path),
            "launcher_ps1": str(launcher_ps1),
            "launcher_sh": str(launcher_sh),
            "mcp_snippet": str(mcp_path) if mcp_path.exists() else None,
        },
        "checksums": checksums,
    }
    bundle_path = out_dir / "bundle.json"
    bundle_path.write_text(json.dumps(bundle, indent=2) + "\n", encoding="utf-8")
    return bundle_path


def package_all(*, sandbox_root: Optional[Path] = None) -> List[Path]:
    bundles: List[Path] = []
    for sid in SERVICE_REGISTRY:
        bundles.append(package_service(sid, sandbox_root=sandbox_root))
    _write_catalog()
    return bundles


def _write_catalog() -> Path:
    payload: Dict[str, Any] = {
        "product": "MESIE Service Catalog",
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "services": [svc.to_dict() for svc in SERVICE_REGISTRY.values()],
        "external": LOOM_EXTERNAL,
        "deploy_targets": ["local-http", "powershell", "cursor-mcp", "docker"],
        "sandbox_root": str(SANDBOX_ROOT),
    }
    CATALOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CATALOG_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return CATALOG_PATH
