#!/usr/bin/env bash
# Medina Surface — generated by mesie.deploy
set -euo pipefail
export MESIE_ROOT="${MESIE_ROOT:-C:\Users\Medin\Multi-Element-Spectral-Intelligence-Engine-MESIE-}"
export MESIE_ROOT="C:\Users\Medin\Multi-Element-Spectral-Intelligence-Engine-MESIE-"
cd "$MESIE_ROOT"
exec C:\Users\Medin\AppData\Local\Programs\Python\Python311-arm64\python.exe scripts/medina_surface.py --serve
