#!/usr/bin/env bash
# MESIE Robotics Satellite — generated by mesie.deploy
set -euo pipefail
export MESIE_ROOT="${MESIE_ROOT:-C:\Users\Medin\Multi-Element-Spectral-Intelligence-Engine-MESIE-}"
export MESIE_ROOT="C:\Users\Medin\Multi-Element-Spectral-Intelligence-Engine-MESIE-"
cd "$MESIE_ROOT"
exec C:\Users\Medin\AppData\Local\Programs\Python\Python311-arm64\python.exe -m mesie.processor.satellite_robotics
