# Robotics Satellite — generated by mesie.deploy
$ErrorActionPreference = "Stop"
$Root = if ($env:MESIE_ROOT) { $env:MESIE_ROOT } else { "C:\Users\Medin\Multi-Element-Spectral-Intelligence-Engine-MESIE-" }
$env:MESIE_ROOT = $Root
$env:MESIE_ROOT = "C:\Users\Medin\Multi-Element-Spectral-Intelligence-Engine-MESIE-"

Write-Host "Robotics Satellite"
Write-Host "  command: C:\Users\Medin\AppData\Local\Programs\Python\Python311-arm64\python.exe -m mesie.processor.satellite_robotics"
Write-Host ""

Set-Location $Root
C:\Users\Medin\AppData\Local\Programs\Python\Python311-arm64\python.exe -m mesie.processor.satellite_robotics
